title: "My awesome post"
description: "This is a description of what I did in my awesome post"
branch: master
main: gallery.ipynb
tags:
  - apples
  - organges
posts:
  - recipe
  - plotly
created_at: -01-01-2016
email: kyle@kyso.io
